version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: Europe/London
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: gatsby
    versions:
    - 2.29.3
    - 2.31.1
    - 2.32.8
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 2.8.0
  - dependency-name: gatsby-link
    versions:
    - 2.10.0
    - 2.8.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.11.2
    - 2.13.4
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.8.1
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.11.0
    - 2.9.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
